spring.application.name=gestion-pacientes
spring.profiles.active=dev

management.metrics.tags.application=SaludPlus

# Habilitar y exponer los endpoints web de Actuator para Prometheus y estado de salud
management.endpoints.web.exposure.include=health,info,prometheus

# Mostrar siempre los detalles completos del estado de los componentes del sistema
management.endpoint.health.show-details=always