# Etapa 1: Construcción usando Maven y Java 21
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copiar los archivos del proyecto para compilar
COPY . .

# Dar permisos al ejecutable de Maven y empaquetar saltando los tests
RUN chmod +x mvnw && ./mvnw clean package -DskipTests

# Etapa 2: Imagen final ligera para correr SaludPlus en producción
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Copiar el .jar generado desde la etapa de construcción
COPY --from=build /app/target/gestion_pacientes-0.0.1-SNAPSHOT.jar app.jar

# Puerto por defecto de Spring Boot
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]